---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack that contains a single elastic beanstalk application

Resources:
  Wordpress:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: Wordpress for use with a PHP Solution Stack

